src/Entity/Books.php
<?php

namespace App\Entity;

use App\Repository\BooksRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BooksRepository::class)]
class Books
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nama_buku = null;

    #[ORM\Column(length: 255)]
    private ?string $genre = null;

    #[ORM\Column]
    private ?int $stock = null;

    #[ORM\Column(length: 255)]
    private ?string $author = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getNamaBuku(): ?string
    {
        return $this->nama_buku;
    }

    public function setNamaBuku(string $nama_buku): static
    {
        $this->nama_buku = $nama_buku;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(string $genre): static
    {
        $this->genre = $genre;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(int $stock): static
    {
        $this->stock = $stock;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): static
    {
        $this->author = $author;

        return $this;
    }
}

src/Controller/BooksController.php
<?php

namespace App\Controller;

use App\Repository\BooksRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

final class BooksController extends AbstractController
{
    #[Route('/books', name: 'app_books')]
    public function index(BooksRepository $books): Response
    {
        $data = $books->getAllBooks();
        return $this->render('books/index.html.twig', [
            'controller_name' => 'BooksController',
            'books' => $data,
        ]);
    }

    #[Route('/create_book', name: 'tambah_buku')]
    public function create(BooksRepository $books): Response
    {
        return $this->render('books/create.html.twig', [
            'controller_name' => 'BooksController',
        ]);
    }

    #[Route('/save_book', name: 'save_book_create', methods: ['POST'])]
    public function store(Request $request, BooksRepository $books): Response
    {
        $data = $request->request->all();
        $books->addBooks($data);
        
        return $this->redirectToRoute('app_books');
    }
    
    #[Route('/edit_book/{id}', name: 'edit_buku')]
    public function edit(int $id, BooksRepository $book){
        $data = $book->getDataBook($id);
        return $this->render('books/edit.html.twig', [
            'books' => $data
        ]);
    }

    #[Route('/update_book/{id}', name: 'save_book_edit', methods: ['POST'])]
    public function update(int $id,Request $request, BooksRepository $books): Response
    {
        $data = $request->request->all();
        $books->editBooks($data, $id);
        
        return $this->redirectToRoute('app_books');
    }
    
    #[Route('/delete_book/{id}', name: 'hapus_buku', methods: ['POST'])]
    public function delete(int $id,Request $request, BooksRepository $book){
        $book->deleteBook($id);
        return $this->redirectToRoute('app_books');
    }

}

templates/books/create.html.twig
{% extends "dashboard/index.html.twig" %}

{% block title %}Create Books {% endblock %}

{% block body %}

<form method="post" action="{{ path('save_book_create') }}">
  <div class="mb-3">
    <label for="nama_buku" class="form-label">Nama Buku</label>
    <input type="text" class="form-control" id="nama_buku" name="nama_buku">
  </div>
  <div class="mb-3">
    <label for="genre" class="form-label">Genre</label>
    <input type="text" class="form-control" id="genre" name="genre">
  </div>
  <div class="mb-3">
    <label for="stock" class="form-label">Stock</label>
    <input type="number" class="form-control" id="stock" name="stock">
  </div>
  <div class="mb-3">
    <label for="author" class="form-label">Pembuat</label>
    <input type="text" class="form-control" id="author" name="author">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
  <a href="{{ path('app_books') }}" class="btn btn-secondary">Kembali</a>
</form>

{% endblock  %}

templates/books/edit.html.twig
{% extends "dashboard/index.html.twig" %}

{% block title %}Edit Books {% endblock %}

{% block body %}

<form method="post" action="{{ path('save_book_edit', {id: books.id}) }}">
  <div class="mb-3">
    <label for="nama_buku" class="form-label">Nama Buku</label>
    <input type="text" class="form-control" id="nama_buku" name="nama_buku" value="{{ books.namaBuku }}">
  </div>
  <div class="mb-3">
    <label for="genre" class="form-label">Genre</label>
    <input type="text" class="form-control" id="genre" name="genre" value="{{ books.genre }}">
  </div>
  <div class="mb-3">
    <label for="stock" class="form-label">Stock</label>
    <input type="number" class="form-control" id="stock" name="stock" value="{{ books.stock }}" max="{{ books.stock }}">
  </div>
  <div class="mb-3">
    <label for="author" class="form-label">Pembuat</label>
    <input type="text" class="form-control" id="author" name="author" value="{{ books.author }}">
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
  <a href="{{ path('app_books') }}" class="btn btn-secondary">Kembali</a>
</form>

{% endblock  %}

templates/books/index.html.twig
{% extends "dashboard/index.html.twig" %}

{% block title %}Books {% endblock %}

{% block body %}
    <a href="{{ path('tambah_buku') }}" class="btn btn-primary" style="margin-bottom: 3%">Tambah Buku</a>
    <table class="table table-striped">
        <thead class="table-dark">
            <tr>
                <th>No</th>
                <th>Judul</th>
                <th>Genre</th>
                <th>Stock</th>
                <th>Penulis</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
                <tr>
                    <td>{{ loop.index }}</td>
                    <td>{{ book.namaBuku }}</td>
                    <td>{{ book.genre }}</td>
                    <td>{{ book.stock }}</td>
                    <td>{{ book.author }}</td>
                    <td>
                        <a href="{{ path('edit_buku', {id: book.id}) }}" class="btn btn-sm btn-warning">Edit</a>
                        <form method="post" action="{{ path('hapus_buku', {id: book.id}) }}" style="display:inline-block;" onsubmit="return confirm('Yakin ingin menghapus buku ini?');">
                            <input type="hidden" name="hapus_id" value="{{ book.id }}">
                            <button class="btn btn-sm btn-danger">Hapus</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock  %}